#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
set +x
umask 077
BROCANTE_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$BROCANTE_ROOT/.dev.vars"
cd "$BROCANTE_ROOT"
for required in node bb; do
  if ! command -v "$required" >/dev/null 2>&1; then
    printf 'This local setup wizard needs %s on PATH. See README.md for manual setup.\n' "$required" >&2
    exit 1
  fi
done
if [[ ! -t 0 ]]; then
  printf 'Run this wizard in an interactive terminal: pnpm setup:github\n' >&2
  exit 1
fi

banner "Connect Brocante to GitHub"

stage "Choose the sign-in origin"
say "Public settings and the session key go into the ignored .dev.vars file."
say "The GitHub client secret will use BB's secure form, never chat or visible input."
say "This configures local development. Production uses Cloudflare variables and secrets."
step "Use the HTTPS URL that opens this running app, or http://localhost:4321 on this machine."
note "Plain HTTP LAN addresses cannot be used for authenticated sessions."
while true; do
  ask APP_URL "Canonical application URL:"
  if node --input-type=module - "$APP_URL" <<'JS'
const input = process.argv[2];
try {
  const url = new URL(input);
  const loopback = ['localhost', '127.0.0.1'].includes(url.hostname);
  if (!(url.protocol === 'https:' || (url.protocol === 'http:' && loopback)) ||
      url.username || url.password || url.pathname !== '/' || url.search || url.hash ||
      ![url.origin, url.origin + '/'].includes(input)) throw new Error();
} catch {
  console.error('Use a bare HTTPS origin, or HTTP localhost/127.0.0.1, without a path.');
  process.exit(1);
}
JS
  then
    APP_URL="${APP_URL%/}"
    break
  fi
done
write_env APP_URL "$APP_URL"

stage "Register the GitHub App"
say "Create a separate development app, such as Brocante Dev plus your account name."
ask BROCANTE_ORGANIZATION "Owning organization slug, or Enter for your personal account:"
while [[ -n "$BROCANTE_ORGANIZATION" && ! "$BROCANTE_ORGANIZATION" =~ ^[A-Za-z0-9-]+$ ]]; do
  ask BROCANTE_ORGANIZATION "Use an organization slug (letters, digits, hyphens), or Enter:"
done
if [[ -n "$BROCANTE_ORGANIZATION" ]]; then
  BROCANTE_REGISTRATION_BASE="https://github.com/organizations/$BROCANTE_ORGANIZATION/settings/apps/new"
else
  BROCANTE_REGISTRATION_BASE="https://github.com/settings/apps/new"
fi
BROCANTE_REGISTRATION_URL="$(node --input-type=module - "$BROCANTE_REGISTRATION_BASE" "$APP_URL" <<'JS'
const url = new URL(process.argv[2]);
const origin = process.argv[3];
url.search = new URLSearchParams({
  name: 'Brocante Dev',
  description: 'A read-only 3D marketplace for repository pull requests.',
  url: origin,
  'callback_urls[]': `${origin}/auth/callback`,
  setup_url: origin,
  request_oauth_on_install: 'false',
  public: 'true',
  webhook_active: 'false',
  pull_requests: 'read',
  metadata: 'read',
}).toString();
process.stdout.write(url.href);
JS
)"
open_url "$BROCANTE_REGISTRATION_URL"
note "The supported fields are prefilled. Check the settings below before creating the app."
step "Name: a unique Brocante development name (34 characters maximum)."
step "Description: A read-only 3D marketplace for repository pull requests."
step "Homepage URL: $APP_URL"
step "Callback URL: $APP_URL/auth/callback"
step "Keep 'Expire user authorization tokens' selected."
step "Leave 'Request user authorization (OAuth) during installation' and Device Flow OFF."
step "Setup URL: $APP_URL (this returns users after installation)."
step "Under Webhook, deselect Active."
step "Repository permissions: Pull requests = Read-only; Metadata = Read-only."
step "Leave other repository, organization, and account permissions at No access."
step "Where can this GitHub App be installed? Select Any account."
step "Click Create GitHub App. No private key or webhook secret is needed."
pause "After GitHub creates the app, press Enter."

stage "Save configuration securely"
step "On the new app's General settings page, copy Client ID (not App ID)."
while true; do
  ask GITHUB_CLIENT_ID "GitHub App Client ID:"
  [[ "$GITHUB_CLIENT_ID" =~ ^[A-Za-z0-9._-]+$ ]] && break
  warn "Enter the Client ID shown in GitHub."
done
step "Copy the app slug from its public URL: https://github.com/apps/<slug>."
while true; do
  ask GITHUB_APP_SLUG "GitHub App slug:"
  [[ "$GITHUB_APP_SLUG" =~ ^[a-z0-9-]+$ ]] && break
  warn "Enter only the slug, not the whole URL."
done
write_env GITHUB_CLIENT_ID "$GITHUB_CLIENT_ID"
write_env GITHUB_APP_SLUG "$GITHUB_APP_SLUG"
BROCANTE_SESSION_KEY="$(_existing SESSION_KEY || true)"
if [[ -z "$BROCANTE_SESSION_KEY" ]]; then
  BROCANTE_SESSION_KEY="$(node -e "process.stdout.write(require('node:crypto').randomBytes(32).toString('base64'))")"
  write_env SESSION_KEY "$BROCANTE_SESSION_KEY"
else
  note "Keeping the existing session encryption key."
fi
unset BROCANTE_SESSION_KEY
step "Under Client secrets, click Generate a new client secret."
step "Copy it into the secure BB form that opens next. Do not paste it into chat."
bb secret request GITHUB_CLIENT_SECRET \
  --purpose "Connect Brocante's local development server to its GitHub App" \
  --describe GITHUB_CLIENT_SECRET "Client secret from the GitHub App's General settings" \
  --write-env "$ENV_FILE"

stage "Install and try a repository"
open_url "https://github.com/apps/$GITHUB_APP_SLUG/installations/new"
step "Install the app on a test account and select a repository you can access."
note "An organization may require an owner to approve the installation."
step "Restart pnpm dev so Cloudflare's local runtime reloads .dev.vars."
step "For an HTTPS development URL, make sure it forwards to this server."
step "Open $APP_URL, select Sign in with GitHub, and authorize Brocante."
step "Enter owner/repository. Try a public repository, then an installed private one."
step "Check that Sign out returns to demo mode and removes private PRs."
note "Production setup is separate: configure the origin and Client ID/slug in Cloudflare,"
note "then set GITHUB_CLIENT_SECRET and a separate SESSION_KEY as Worker secrets."
finish
say "Local configuration saved. Complete the browser checks above to verify live access."
say "No deployment or live GitHub access test was performed by this wizard."
